// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbukqlcbcdqegquigkom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtidWtxbGNiY2RxZWdxdWlna29tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1MjM0NjYsImV4cCI6MjA1NjA5OTQ2Nn0.4n1d5SOVkknU6Il9seIZUjf4fl1-HylasNmjtDw4xJ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);